//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Latekick.BOL.Latekick {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Latekick_Card {
        
        private Course courseField;
        
        private Race[] raceField;
        
        private System.DateTime raceDateField;
        
        private string numberOfRacesField;
        
        /// <remarks/>
        public Course Course {
            get {
                return this.courseField;
            }
            set {
                this.courseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Race")]
        public Race[] Race {
            get {
                return this.raceField;
            }
            set {
                this.raceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime RaceDate {
            get {
                return this.raceDateField;
            }
            set {
                this.raceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string NumberOfRaces {
            get {
                return this.numberOfRacesField;
            }
            set {
                this.numberOfRacesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Course {
        
        private string courseCodeField;
        
        private string courseNameField;
        
        public Course() {
            this.courseNameField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string CourseCode {
            get {
                return this.courseCodeField;
            }
            set {
                this.courseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CourseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Race {
        
        private RaceInfo raceInfoField;
        
        private Entry[] entryField;
        
        private System.DateTime raceDateField;
        
        private string raceNumberField;
        
        /// <remarks/>
        public RaceInfo RaceInfo {
            get {
                return this.raceInfoField;
            }
            set {
                this.raceInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entry")]
        public Entry[] Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime RaceDate {
            get {
                return this.raceDateField;
            }
            set {
                this.raceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string RaceNumber {
            get {
                return this.raceNumberField;
            }
            set {
                this.raceNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RaceInfo {
        
        private string breedField;
        
        private string dayEveField;
        
        private string raceTypeField;
        
        private string raceTypeLongField;
        
        private int purseField;
        
        private string raceDescriptionField;
        
        private string ageSexRestrictionsField;
        
        private double distanceFurlongsField;
        
        private double distanceYardsField;
        
        private string courseCodeField;
        
        private string courseNameField;
        
        private int raceNumberField;
        
        private string surfaceField;
        
        private int classRatingField;
        
        private int maxEarlyField;
        
        private int maxMiddleField;
        
        private int maxLateField;
        
        private int maxAverageField;
        
        private int maxRecentField;
        
        private double maxPaceField;
        
        private int brisPar_SpeedFigField;
        
        private int brisPar_2FField;
        
        private int brisPar_4FField;
        
        private int brisPar_6FField;
        
        private int brisPar_LateField;
        
        private string goingField;
        
        private string weatherField;
        
        private string postTimeField;
        
        private int numberOfHorsesField;
        
        private string betTypesField;
        
        private CD_Profile cD_ProfileField;
        
        public RaceInfo() {
            this.raceTypeField = "";
            this.raceTypeLongField = "";
            this.courseNameField = "";
        }
        
        /// <remarks/>
        public string Breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string DayEve {
            get {
                return this.dayEveField;
            }
            set {
                this.dayEveField = value;
            }
        }
        
        /// <remarks/>
        public string RaceType {
            get {
                return this.raceTypeField;
            }
            set {
                this.raceTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RaceTypeLong {
            get {
                return this.raceTypeLongField;
            }
            set {
                this.raceTypeLongField = value;
            }
        }
        
        /// <remarks/>
        public int Purse {
            get {
                return this.purseField;
            }
            set {
                this.purseField = value;
            }
        }
        
        /// <remarks/>
        public string RaceDescription {
            get {
                return this.raceDescriptionField;
            }
            set {
                this.raceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string AgeSexRestrictions {
            get {
                return this.ageSexRestrictionsField;
            }
            set {
                this.ageSexRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public double DistanceFurlongs {
            get {
                return this.distanceFurlongsField;
            }
            set {
                this.distanceFurlongsField = value;
            }
        }
        
        /// <remarks/>
        public double DistanceYards {
            get {
                return this.distanceYardsField;
            }
            set {
                this.distanceYardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string CourseCode {
            get {
                return this.courseCodeField;
            }
            set {
                this.courseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CourseName {
            get {
                return this.courseNameField;
            }
            set {
                this.courseNameField = value;
            }
        }
        
        /// <remarks/>
        public int RaceNumber {
            get {
                return this.raceNumberField;
            }
            set {
                this.raceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string Surface {
            get {
                return this.surfaceField;
            }
            set {
                this.surfaceField = value;
            }
        }
        
        /// <remarks/>
        public int ClassRating {
            get {
                return this.classRatingField;
            }
            set {
                this.classRatingField = value;
            }
        }
        
        /// <remarks/>
        public int MaxEarly {
            get {
                return this.maxEarlyField;
            }
            set {
                this.maxEarlyField = value;
            }
        }
        
        /// <remarks/>
        public int MaxMiddle {
            get {
                return this.maxMiddleField;
            }
            set {
                this.maxMiddleField = value;
            }
        }
        
        /// <remarks/>
        public int MaxLate {
            get {
                return this.maxLateField;
            }
            set {
                this.maxLateField = value;
            }
        }
        
        /// <remarks/>
        public int MaxAverage {
            get {
                return this.maxAverageField;
            }
            set {
                this.maxAverageField = value;
            }
        }
        
        /// <remarks/>
        public int MaxRecent {
            get {
                return this.maxRecentField;
            }
            set {
                this.maxRecentField = value;
            }
        }
        
        /// <remarks/>
        public double MaxPace {
            get {
                return this.maxPaceField;
            }
            set {
                this.maxPaceField = value;
            }
        }
        
        /// <remarks/>
        public int BrisPar_SpeedFig {
            get {
                return this.brisPar_SpeedFigField;
            }
            set {
                this.brisPar_SpeedFigField = value;
            }
        }
        
        /// <remarks/>
        public int BrisPar_2F {
            get {
                return this.brisPar_2FField;
            }
            set {
                this.brisPar_2FField = value;
            }
        }
        
        /// <remarks/>
        public int BrisPar_4F {
            get {
                return this.brisPar_4FField;
            }
            set {
                this.brisPar_4FField = value;
            }
        }
        
        /// <remarks/>
        public int BrisPar_6F {
            get {
                return this.brisPar_6FField;
            }
            set {
                this.brisPar_6FField = value;
            }
        }
        
        /// <remarks/>
        public int BrisPar_Late {
            get {
                return this.brisPar_LateField;
            }
            set {
                this.brisPar_LateField = value;
            }
        }
        
        /// <remarks/>
        public string Going {
            get {
                return this.goingField;
            }
            set {
                this.goingField = value;
            }
        }
        
        /// <remarks/>
        public string Weather {
            get {
                return this.weatherField;
            }
            set {
                this.weatherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string PostTime {
            get {
                return this.postTimeField;
            }
            set {
                this.postTimeField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfHorses {
            get {
                return this.numberOfHorsesField;
            }
            set {
                this.numberOfHorsesField = value;
            }
        }
        
        /// <remarks/>
        public string BetTypes {
            get {
                return this.betTypesField;
            }
            set {
                this.betTypesField = value;
            }
        }
        
        /// <remarks/>
        public CD_Profile CD_Profile {
            get {
                return this.cD_ProfileField;
            }
            set {
                this.cD_ProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class CD_Profile {
        
        private int runs_AllField;
        
        private int paceWins_AllField;
        
        private int stalkWins_AllField;
        
        private int closeWins_AllField;
        
        private int runs_RecentField;
        
        private int paceWins_RecentField;
        
        private int stalkWins_RecentField;
        
        private int closeWins_RecentField;
        
        /// <remarks/>
        public int Runs_All {
            get {
                return this.runs_AllField;
            }
            set {
                this.runs_AllField = value;
            }
        }
        
        /// <remarks/>
        public int PaceWins_All {
            get {
                return this.paceWins_AllField;
            }
            set {
                this.paceWins_AllField = value;
            }
        }
        
        /// <remarks/>
        public int StalkWins_All {
            get {
                return this.stalkWins_AllField;
            }
            set {
                this.stalkWins_AllField = value;
            }
        }
        
        /// <remarks/>
        public int CloseWins_All {
            get {
                return this.closeWins_AllField;
            }
            set {
                this.closeWins_AllField = value;
            }
        }
        
        /// <remarks/>
        public int Runs_Recent {
            get {
                return this.runs_RecentField;
            }
            set {
                this.runs_RecentField = value;
            }
        }
        
        /// <remarks/>
        public int PaceWins_Recent {
            get {
                return this.paceWins_RecentField;
            }
            set {
                this.paceWins_RecentField = value;
            }
        }
        
        /// <remarks/>
        public int StalkWins_Recent {
            get {
                return this.stalkWins_RecentField;
            }
            set {
                this.stalkWins_RecentField = value;
            }
        }
        
        /// <remarks/>
        public int CloseWins_Recent {
            get {
                return this.closeWins_RecentField;
            }
            set {
                this.closeWins_RecentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Entry {
        
        private string horseNameField;
        
        private int weightField;
        
        private int apprenticeAllowanceField;
        
        private int ageField;
        
        private string genderField;
        
        private string sireField;
        
        private string damField;
        
        private string damSireField;
        
        private string medicationField;
        
        private string equipmentField;
        
        private string saddleClothNoField;
        
        private int drawField;
        
        private int claimPriceField;
        
        private string jockeyNameField;
        
        private string trainerNameField;
        
        private string ownerNameField;
        
        private double mlField;
        
        private double lK_OddsField;
        
        private Stats statsField;
        
        private BrisStats brisStatsField;
        
        private Earnings earningsField;
        
        private ProjectedRatings projectedRatingsField;
        
        private PPs pPsField;
        
        private Workouts workoutsField;
        
        private RunningStyle runningStyleField;
        
        /// <remarks/>
        public string HorseName {
            get {
                return this.horseNameField;
            }
            set {
                this.horseNameField = value;
            }
        }
        
        /// <remarks/>
        public int Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int ApprenticeAllowance {
            get {
                return this.apprenticeAllowanceField;
            }
            set {
                this.apprenticeAllowanceField = value;
            }
        }
        
        /// <remarks/>
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string Sire {
            get {
                return this.sireField;
            }
            set {
                this.sireField = value;
            }
        }
        
        /// <remarks/>
        public string Dam {
            get {
                return this.damField;
            }
            set {
                this.damField = value;
            }
        }
        
        /// <remarks/>
        public string DamSire {
            get {
                return this.damSireField;
            }
            set {
                this.damSireField = value;
            }
        }
        
        /// <remarks/>
        public string Medication {
            get {
                return this.medicationField;
            }
            set {
                this.medicationField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        public string SaddleClothNo {
            get {
                return this.saddleClothNoField;
            }
            set {
                this.saddleClothNoField = value;
            }
        }
        
        /// <remarks/>
        public int Draw {
            get {
                return this.drawField;
            }
            set {
                this.drawField = value;
            }
        }
        
        /// <remarks/>
        public int ClaimPrice {
            get {
                return this.claimPriceField;
            }
            set {
                this.claimPriceField = value;
            }
        }
        
        /// <remarks/>
        public string JockeyName {
            get {
                return this.jockeyNameField;
            }
            set {
                this.jockeyNameField = value;
            }
        }
        
        /// <remarks/>
        public string TrainerName {
            get {
                return this.trainerNameField;
            }
            set {
                this.trainerNameField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerName {
            get {
                return this.ownerNameField;
            }
            set {
                this.ownerNameField = value;
            }
        }
        
        /// <remarks/>
        public double ML {
            get {
                return this.mlField;
            }
            set {
                this.mlField = value;
            }
        }
        
        /// <remarks/>
        public double LK_Odds {
            get {
                return this.lK_OddsField;
            }
            set {
                this.lK_OddsField = value;
            }
        }
        
        /// <remarks/>
        public Stats Stats {
            get {
                return this.statsField;
            }
            set {
                this.statsField = value;
            }
        }
        
        /// <remarks/>
        public BrisStats BrisStats {
            get {
                return this.brisStatsField;
            }
            set {
                this.brisStatsField = value;
            }
        }
        
        /// <remarks/>
        public Earnings Earnings {
            get {
                return this.earningsField;
            }
            set {
                this.earningsField = value;
            }
        }
        
        /// <remarks/>
        public ProjectedRatings ProjectedRatings {
            get {
                return this.projectedRatingsField;
            }
            set {
                this.projectedRatingsField = value;
            }
        }
        
        /// <remarks/>
        public PPs PPs {
            get {
                return this.pPsField;
            }
            set {
                this.pPsField = value;
            }
        }
        
        /// <remarks/>
        public Workouts Workouts {
            get {
                return this.workoutsField;
            }
            set {
                this.workoutsField = value;
            }
        }
        
        /// <remarks/>
        public RunningStyle RunningStyle {
            get {
                return this.runningStyleField;
            }
            set {
                this.runningStyleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Stats {
        
        private int lifeTime_RunsField;
        
        private int lifeTime_WinField;
        
        private int lifeTime_PlaceField;
        
        private int lifeTime_ShowField;
        
        private int thisYear_RunsField;
        
        private int thisYear_WinField;
        
        private int thisYear_PlaceField;
        
        private int thisYear_ShowField;
        
        private int lastYear_RunsField;
        
        private int lastYear_WinField;
        
        private int lastYear_PlaceField;
        
        private int lastYear_ShowField;
        
        private int course_RunsField;
        
        private int course_WinField;
        
        private int course_PlaceField;
        
        private int course_ShowField;
        
        private int dirt_RunsField;
        
        private int dirt_WinField;
        
        private int dirt_PlaceField;
        
        private int dirt_ShowField;
        
        private int turf_RunsField;
        
        private int turf_WinField;
        
        private int turf_PlaceField;
        
        private int turf_ShowField;
        
        private int aW_RunsField;
        
        private int aW_WinField;
        
        private int aW_PlaceField;
        
        private int aW_ShowField;
        
        private int wet_RunsField;
        
        private int wet_WinField;
        
        private int wet_PlaceField;
        
        private int wet_ShowField;
        
        private int distance_RunsField;
        
        private int distance_WinField;
        
        private int distance_PlaceField;
        
        private int distance_ShowField;
        
        private int jockey_Runs_MeetField;
        
        private int jockey_Win_MeetField;
        
        private int jockey_Place_MeetField;
        
        private int jockey_Show_MeetField;
        
        private int jockey_30d_RunsField;
        
        private int jockey_30d_WinField;
        
        private int jockey_30d_PlaceField;
        
        private int jockey_30d_ShowField;
        
        private int trainer_Runs_MeetField;
        
        private int trainer_Win_MeetField;
        
        private int trainer_Place_MeetField;
        
        private int trainer_Show_MeetField;
        
        private int trainer_30d_RunsField;
        
        private int trainer_30d_WinField;
        
        private int trainer_30d_PlaceField;
        
        private int trainer_30d_ShowField;
        
        private string trainer_ThisYearField;
        
        private string trainer_LastYearField;
        
        private string jockey_ThisYearField;
        
        private string jockey_LastYearField;
        
        /// <remarks/>
        public int LifeTime_Runs {
            get {
                return this.lifeTime_RunsField;
            }
            set {
                this.lifeTime_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int LifeTime_Win {
            get {
                return this.lifeTime_WinField;
            }
            set {
                this.lifeTime_WinField = value;
            }
        }
        
        /// <remarks/>
        public int LifeTime_Place {
            get {
                return this.lifeTime_PlaceField;
            }
            set {
                this.lifeTime_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int LifeTime_Show {
            get {
                return this.lifeTime_ShowField;
            }
            set {
                this.lifeTime_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int ThisYear_Runs {
            get {
                return this.thisYear_RunsField;
            }
            set {
                this.thisYear_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int ThisYear_Win {
            get {
                return this.thisYear_WinField;
            }
            set {
                this.thisYear_WinField = value;
            }
        }
        
        /// <remarks/>
        public int ThisYear_Place {
            get {
                return this.thisYear_PlaceField;
            }
            set {
                this.thisYear_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int ThisYear_Show {
            get {
                return this.thisYear_ShowField;
            }
            set {
                this.thisYear_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int LastYear_Runs {
            get {
                return this.lastYear_RunsField;
            }
            set {
                this.lastYear_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int LastYear_Win {
            get {
                return this.lastYear_WinField;
            }
            set {
                this.lastYear_WinField = value;
            }
        }
        
        /// <remarks/>
        public int LastYear_Place {
            get {
                return this.lastYear_PlaceField;
            }
            set {
                this.lastYear_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int LastYear_Show {
            get {
                return this.lastYear_ShowField;
            }
            set {
                this.lastYear_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int Course_Runs {
            get {
                return this.course_RunsField;
            }
            set {
                this.course_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int Course_Win {
            get {
                return this.course_WinField;
            }
            set {
                this.course_WinField = value;
            }
        }
        
        /// <remarks/>
        public int Course_Place {
            get {
                return this.course_PlaceField;
            }
            set {
                this.course_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Course_Show {
            get {
                return this.course_ShowField;
            }
            set {
                this.course_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int Dirt_Runs {
            get {
                return this.dirt_RunsField;
            }
            set {
                this.dirt_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int Dirt_Win {
            get {
                return this.dirt_WinField;
            }
            set {
                this.dirt_WinField = value;
            }
        }
        
        /// <remarks/>
        public int Dirt_Place {
            get {
                return this.dirt_PlaceField;
            }
            set {
                this.dirt_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Dirt_Show {
            get {
                return this.dirt_ShowField;
            }
            set {
                this.dirt_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int Turf_Runs {
            get {
                return this.turf_RunsField;
            }
            set {
                this.turf_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int Turf_Win {
            get {
                return this.turf_WinField;
            }
            set {
                this.turf_WinField = value;
            }
        }
        
        /// <remarks/>
        public int Turf_Place {
            get {
                return this.turf_PlaceField;
            }
            set {
                this.turf_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Turf_Show {
            get {
                return this.turf_ShowField;
            }
            set {
                this.turf_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int AW_Runs {
            get {
                return this.aW_RunsField;
            }
            set {
                this.aW_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int AW_Win {
            get {
                return this.aW_WinField;
            }
            set {
                this.aW_WinField = value;
            }
        }
        
        /// <remarks/>
        public int AW_Place {
            get {
                return this.aW_PlaceField;
            }
            set {
                this.aW_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int AW_Show {
            get {
                return this.aW_ShowField;
            }
            set {
                this.aW_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int Wet_Runs {
            get {
                return this.wet_RunsField;
            }
            set {
                this.wet_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int Wet_Win {
            get {
                return this.wet_WinField;
            }
            set {
                this.wet_WinField = value;
            }
        }
        
        /// <remarks/>
        public int Wet_Place {
            get {
                return this.wet_PlaceField;
            }
            set {
                this.wet_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Wet_Show {
            get {
                return this.wet_ShowField;
            }
            set {
                this.wet_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int Distance_Runs {
            get {
                return this.distance_RunsField;
            }
            set {
                this.distance_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int Distance_Win {
            get {
                return this.distance_WinField;
            }
            set {
                this.distance_WinField = value;
            }
        }
        
        /// <remarks/>
        public int Distance_Place {
            get {
                return this.distance_PlaceField;
            }
            set {
                this.distance_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Distance_Show {
            get {
                return this.distance_ShowField;
            }
            set {
                this.distance_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_Runs_Meet {
            get {
                return this.jockey_Runs_MeetField;
            }
            set {
                this.jockey_Runs_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_Win_Meet {
            get {
                return this.jockey_Win_MeetField;
            }
            set {
                this.jockey_Win_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_Place_Meet {
            get {
                return this.jockey_Place_MeetField;
            }
            set {
                this.jockey_Place_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_Show_Meet {
            get {
                return this.jockey_Show_MeetField;
            }
            set {
                this.jockey_Show_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_30d_Runs {
            get {
                return this.jockey_30d_RunsField;
            }
            set {
                this.jockey_30d_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_30d_Win {
            get {
                return this.jockey_30d_WinField;
            }
            set {
                this.jockey_30d_WinField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_30d_Place {
            get {
                return this.jockey_30d_PlaceField;
            }
            set {
                this.jockey_30d_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Jockey_30d_Show {
            get {
                return this.jockey_30d_ShowField;
            }
            set {
                this.jockey_30d_ShowField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_Runs_Meet {
            get {
                return this.trainer_Runs_MeetField;
            }
            set {
                this.trainer_Runs_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_Win_Meet {
            get {
                return this.trainer_Win_MeetField;
            }
            set {
                this.trainer_Win_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_Place_Meet {
            get {
                return this.trainer_Place_MeetField;
            }
            set {
                this.trainer_Place_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_Show_Meet {
            get {
                return this.trainer_Show_MeetField;
            }
            set {
                this.trainer_Show_MeetField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_30d_Runs {
            get {
                return this.trainer_30d_RunsField;
            }
            set {
                this.trainer_30d_RunsField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_30d_Win {
            get {
                return this.trainer_30d_WinField;
            }
            set {
                this.trainer_30d_WinField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_30d_Place {
            get {
                return this.trainer_30d_PlaceField;
            }
            set {
                this.trainer_30d_PlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Trainer_30d_Show {
            get {
                return this.trainer_30d_ShowField;
            }
            set {
                this.trainer_30d_ShowField = value;
            }
        }
        
        /// <remarks/>
        public string Trainer_ThisYear {
            get {
                return this.trainer_ThisYearField;
            }
            set {
                this.trainer_ThisYearField = value;
            }
        }
        
        /// <remarks/>
        public string Trainer_LastYear {
            get {
                return this.trainer_LastYearField;
            }
            set {
                this.trainer_LastYearField = value;
            }
        }
        
        /// <remarks/>
        public string Jockey_ThisYear {
            get {
                return this.jockey_ThisYearField;
            }
            set {
                this.jockey_ThisYearField = value;
            }
        }
        
        /// <remarks/>
        public string Jockey_LastYear {
            get {
                return this.jockey_LastYearField;
            }
            set {
                this.jockey_LastYearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BrisStats {
        
        private BrisStat[] brisStatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BrisStat")]
        public BrisStat[] BrisStat {
            get {
                return this.brisStatField;
            }
            set {
                this.brisStatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BrisStat {
        
        private string brisStatCategoryField;
        
        private int runsField;
        
        private double winPctField;
        
        private double iTMField;
        
        private double rOIField;
        
        public BrisStat() {
            this.brisStatCategoryField = "";
        }
        
        /// <remarks/>
        public string BrisStatCategory {
            get {
                return this.brisStatCategoryField;
            }
            set {
                this.brisStatCategoryField = value;
            }
        }
        
        /// <remarks/>
        public int Runs {
            get {
                return this.runsField;
            }
            set {
                this.runsField = value;
            }
        }
        
        /// <remarks/>
        public double WinPct {
            get {
                return this.winPctField;
            }
            set {
                this.winPctField = value;
            }
        }
        
        /// <remarks/>
        public double ITM {
            get {
                return this.iTMField;
            }
            set {
                this.iTMField = value;
            }
        }
        
        /// <remarks/>
        public double ROI {
            get {
                return this.rOIField;
            }
            set {
                this.rOIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Earnings {
        
        private int earningsLifeTimeField;
        
        private int earningsThisYearField;
        
        private int earningsLastYearField;
        
        private int earningsCourseField;
        
        private int earningsDirtField;
        
        private int earningsTurfField;
        
        private int earningsAWField;
        
        private int earningsWetField;
        
        private int earningsDistanceField;
        
        /// <remarks/>
        public int EarningsLifeTime {
            get {
                return this.earningsLifeTimeField;
            }
            set {
                this.earningsLifeTimeField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsThisYear {
            get {
                return this.earningsThisYearField;
            }
            set {
                this.earningsThisYearField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsLastYear {
            get {
                return this.earningsLastYearField;
            }
            set {
                this.earningsLastYearField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsCourse {
            get {
                return this.earningsCourseField;
            }
            set {
                this.earningsCourseField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsDirt {
            get {
                return this.earningsDirtField;
            }
            set {
                this.earningsDirtField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsTurf {
            get {
                return this.earningsTurfField;
            }
            set {
                this.earningsTurfField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsAW {
            get {
                return this.earningsAWField;
            }
            set {
                this.earningsAWField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsWet {
            get {
                return this.earningsWetField;
            }
            set {
                this.earningsWetField = value;
            }
        }
        
        /// <remarks/>
        public int EarningsDistance {
            get {
                return this.earningsDistanceField;
            }
            set {
                this.earningsDistanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ProjectedRatings {
        
        private double earlyField;
        
        private double middleField;
        
        private double lateField;
        
        private double dashField;
        
        private double goldenField;
        
        private double averageField;
        
        private double recentField;
        
        private double quirinField;
        
        /// <remarks/>
        public double Early {
            get {
                return this.earlyField;
            }
            set {
                this.earlyField = value;
            }
        }
        
        /// <remarks/>
        public double Middle {
            get {
                return this.middleField;
            }
            set {
                this.middleField = value;
            }
        }
        
        /// <remarks/>
        public double Late {
            get {
                return this.lateField;
            }
            set {
                this.lateField = value;
            }
        }
        
        /// <remarks/>
        public double Dash {
            get {
                return this.dashField;
            }
            set {
                this.dashField = value;
            }
        }
        
        /// <remarks/>
        public double Golden {
            get {
                return this.goldenField;
            }
            set {
                this.goldenField = value;
            }
        }
        
        /// <remarks/>
        public double Average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
            }
        }
        
        /// <remarks/>
        public double Recent {
            get {
                return this.recentField;
            }
            set {
                this.recentField = value;
            }
        }
        
        /// <remarks/>
        public double Quirin {
            get {
                return this.quirinField;
            }
            set {
                this.quirinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PPs {
        
        private PP[] ppField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PP")]
        public PP[] PP {
            get {
                return this.ppField;
            }
            set {
                this.ppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PP {
        
        private System.DateTime raceDateField;
        
        private string breedField;
        
        private string countryField;
        
        private string courseCodeField;
        
        private int raceNumberField;
        
        private double distanceFurlongsField;
        
        private double distanceYardsField;
        
        private string surfaceField;
        
        private string goingField;
        
        private int purseField;
        
        private int claimPriceField;
        
        private int drawField;
        
        private double finalTimeField;
        
        private string officialFinishField;
        
        private string officialPositionTextField;
        
        private string finish123Field;
        
        private double distanceBeatenField;
        
        private double oddsField;
        
        private int weightField;
        
        private string tripCommentField;
        
        private string winNameField;
        
        private string placeNameField;
        
        private string showNameField;
        
        private string jockeyNameField;
        
        private string trainerNameField;
        
        private string ageSexRestrictionsField;
        
        private string medicationField;
        
        private string equipmentField;
        
        private PP_Brisnet pP_BrisnetField;
        
        private PP_Trackmaster pP_TrackmasterField;
        
        private PP_Latekick pP_LatekickField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime RaceDate {
            get {
                return this.raceDateField;
            }
            set {
                this.raceDateField = value;
            }
        }
        
        /// <remarks/>
        public string Breed {
            get {
                return this.breedField;
            }
            set {
                this.breedField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string CourseCode {
            get {
                return this.courseCodeField;
            }
            set {
                this.courseCodeField = value;
            }
        }
        
        /// <remarks/>
        public int RaceNumber {
            get {
                return this.raceNumberField;
            }
            set {
                this.raceNumberField = value;
            }
        }
        
        /// <remarks/>
        public double DistanceFurlongs {
            get {
                return this.distanceFurlongsField;
            }
            set {
                this.distanceFurlongsField = value;
            }
        }
        
        /// <remarks/>
        public double DistanceYards {
            get {
                return this.distanceYardsField;
            }
            set {
                this.distanceYardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string Surface {
            get {
                return this.surfaceField;
            }
            set {
                this.surfaceField = value;
            }
        }
        
        /// <remarks/>
        public string Going {
            get {
                return this.goingField;
            }
            set {
                this.goingField = value;
            }
        }
        
        /// <remarks/>
        public int Purse {
            get {
                return this.purseField;
            }
            set {
                this.purseField = value;
            }
        }
        
        /// <remarks/>
        public int ClaimPrice {
            get {
                return this.claimPriceField;
            }
            set {
                this.claimPriceField = value;
            }
        }
        
        /// <remarks/>
        public int Draw {
            get {
                return this.drawField;
            }
            set {
                this.drawField = value;
            }
        }
        
        /// <remarks/>
        public double FinalTime {
            get {
                return this.finalTimeField;
            }
            set {
                this.finalTimeField = value;
            }
        }
        
        /// <remarks/>
        public string OfficialFinish {
            get {
                return this.officialFinishField;
            }
            set {
                this.officialFinishField = value;
            }
        }
        
        /// <remarks/>
        public string OfficialPositionText {
            get {
                return this.officialPositionTextField;
            }
            set {
                this.officialPositionTextField = value;
            }
        }
        
        /// <remarks/>
        public string Finish123 {
            get {
                return this.finish123Field;
            }
            set {
                this.finish123Field = value;
            }
        }
        
        /// <remarks/>
        public double DistanceBeaten {
            get {
                return this.distanceBeatenField;
            }
            set {
                this.distanceBeatenField = value;
            }
        }
        
        /// <remarks/>
        public double Odds {
            get {
                return this.oddsField;
            }
            set {
                this.oddsField = value;
            }
        }
        
        /// <remarks/>
        public int Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public string TripComment {
            get {
                return this.tripCommentField;
            }
            set {
                this.tripCommentField = value;
            }
        }
        
        /// <remarks/>
        public string WinName {
            get {
                return this.winNameField;
            }
            set {
                this.winNameField = value;
            }
        }
        
        /// <remarks/>
        public string PlaceName {
            get {
                return this.placeNameField;
            }
            set {
                this.placeNameField = value;
            }
        }
        
        /// <remarks/>
        public string ShowName {
            get {
                return this.showNameField;
            }
            set {
                this.showNameField = value;
            }
        }
        
        /// <remarks/>
        public string JockeyName {
            get {
                return this.jockeyNameField;
            }
            set {
                this.jockeyNameField = value;
            }
        }
        
        /// <remarks/>
        public string TrainerName {
            get {
                return this.trainerNameField;
            }
            set {
                this.trainerNameField = value;
            }
        }
        
        /// <remarks/>
        public string AgeSexRestrictions {
            get {
                return this.ageSexRestrictionsField;
            }
            set {
                this.ageSexRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public string Medication {
            get {
                return this.medicationField;
            }
            set {
                this.medicationField = value;
            }
        }
        
        /// <remarks/>
        public string Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        public PP_Brisnet PP_Brisnet {
            get {
                return this.pP_BrisnetField;
            }
            set {
                this.pP_BrisnetField = value;
            }
        }
        
        /// <remarks/>
        public PP_Trackmaster PP_Trackmaster {
            get {
                return this.pP_TrackmasterField;
            }
            set {
                this.pP_TrackmasterField = value;
            }
        }
        
        /// <remarks/>
        public PP_Latekick PP_Latekick {
            get {
                return this.pP_LatekickField;
            }
            set {
                this.pP_LatekickField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PP_Brisnet {
        
        private int speedFigField;
        
        private int paceFig_2FField;
        
        private int paceFig_4FField;
        
        private int paceFig_6FField;
        
        private int paceFig_8FField;
        
        private int paceFig_10FField;
        
        private int paceFig_LateField;
        
        private string tripCommentField;
        
        /// <remarks/>
        public int SpeedFig {
            get {
                return this.speedFigField;
            }
            set {
                this.speedFigField = value;
            }
        }
        
        /// <remarks/>
        public int PaceFig_2F {
            get {
                return this.paceFig_2FField;
            }
            set {
                this.paceFig_2FField = value;
            }
        }
        
        /// <remarks/>
        public int PaceFig_4F {
            get {
                return this.paceFig_4FField;
            }
            set {
                this.paceFig_4FField = value;
            }
        }
        
        /// <remarks/>
        public int PaceFig_6F {
            get {
                return this.paceFig_6FField;
            }
            set {
                this.paceFig_6FField = value;
            }
        }
        
        /// <remarks/>
        public int PaceFig_8F {
            get {
                return this.paceFig_8FField;
            }
            set {
                this.paceFig_8FField = value;
            }
        }
        
        /// <remarks/>
        public int PaceFig_10F {
            get {
                return this.paceFig_10FField;
            }
            set {
                this.paceFig_10FField = value;
            }
        }
        
        /// <remarks/>
        public int PaceFig_Late {
            get {
                return this.paceFig_LateField;
            }
            set {
                this.paceFig_LateField = value;
            }
        }
        
        /// <remarks/>
        public string TripComment {
            get {
                return this.tripCommentField;
            }
            set {
                this.tripCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PP_Trackmaster {
        
        private int speedFigField;
        
        private string tripCommentField;
        
        private string longTripCommentField;
        
        /// <remarks/>
        public int SpeedFig {
            get {
                return this.speedFigField;
            }
            set {
                this.speedFigField = value;
            }
        }
        
        /// <remarks/>
        public string TripComment {
            get {
                return this.tripCommentField;
            }
            set {
                this.tripCommentField = value;
            }
        }
        
        /// <remarks/>
        public string LongTripComment {
            get {
                return this.longTripCommentField;
            }
            set {
                this.longTripCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PP_Latekick {
        
        private string raceTypeField;
        
        private int classRating_GMRField;
        
        private string finish123_GMRField;
        
        private double earlyField;
        
        private double middleField;
        
        private double lateField;
        
        private double dashField;
        
        private double goldenField;
        
        private double latekickField;
        
        private double lateSpeedField;
        
        public PP_Latekick() {
            this.raceTypeField = "";
            this.finish123_GMRField = " ";
        }
        
        /// <remarks/>
        public string RaceType {
            get {
                return this.raceTypeField;
            }
            set {
                this.raceTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ClassRating_GMR {
            get {
                return this.classRating_GMRField;
            }
            set {
                this.classRating_GMRField = value;
            }
        }
        
        /// <remarks/>
        public string Finish123_GMR {
            get {
                return this.finish123_GMRField;
            }
            set {
                this.finish123_GMRField = value;
            }
        }
        
        /// <remarks/>
        public double Early {
            get {
                return this.earlyField;
            }
            set {
                this.earlyField = value;
            }
        }
        
        /// <remarks/>
        public double Middle {
            get {
                return this.middleField;
            }
            set {
                this.middleField = value;
            }
        }
        
        /// <remarks/>
        public double Late {
            get {
                return this.lateField;
            }
            set {
                this.lateField = value;
            }
        }
        
        /// <remarks/>
        public double Dash {
            get {
                return this.dashField;
            }
            set {
                this.dashField = value;
            }
        }
        
        /// <remarks/>
        public double Golden {
            get {
                return this.goldenField;
            }
            set {
                this.goldenField = value;
            }
        }
        
        /// <remarks/>
        public double Latekick {
            get {
                return this.latekickField;
            }
            set {
                this.latekickField = value;
            }
        }
        
        /// <remarks/>
        public double LateSpeed {
            get {
                return this.lateSpeedField;
            }
            set {
                this.lateSpeedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Workouts {
        
        private Workout[] workoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Workout")]
        public Workout[] Workout {
            get {
                return this.workoutField;
            }
            set {
                this.workoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Workout {
        
        private System.DateTime workDateField;
        
        private string workTrackField;
        
        private double workDistanceField;
        
        private string workGoingField;
        
        private string workDescriptionField;
        
        private string workSurfaceField;
        
        private double workTimeField;
        
        private string workRankField;
        
        private int workRatingField;
        
        private int workFromGateField;
        
        private string workMatesField;
        
        private string workDaysAgoField;
        
        public Workout() {
            this.workMatesField = "";
            this.workDaysAgoField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime WorkDate {
            get {
                return this.workDateField;
            }
            set {
                this.workDateField = value;
            }
        }
        
        /// <remarks/>
        public string WorkTrack {
            get {
                return this.workTrackField;
            }
            set {
                this.workTrackField = value;
            }
        }
        
        /// <remarks/>
        public double WorkDistance {
            get {
                return this.workDistanceField;
            }
            set {
                this.workDistanceField = value;
            }
        }
        
        /// <remarks/>
        public string WorkGoing {
            get {
                return this.workGoingField;
            }
            set {
                this.workGoingField = value;
            }
        }
        
        /// <remarks/>
        public string WorkDescription {
            get {
                return this.workDescriptionField;
            }
            set {
                this.workDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string WorkSurface {
            get {
                return this.workSurfaceField;
            }
            set {
                this.workSurfaceField = value;
            }
        }
        
        /// <remarks/>
        public double WorkTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
            }
        }
        
        /// <remarks/>
        public string WorkRank {
            get {
                return this.workRankField;
            }
            set {
                this.workRankField = value;
            }
        }
        
        /// <remarks/>
        public int WorkRating {
            get {
                return this.workRatingField;
            }
            set {
                this.workRatingField = value;
            }
        }
        
        /// <remarks/>
        public int WorkFromGate {
            get {
                return this.workFromGateField;
            }
            set {
                this.workFromGateField = value;
            }
        }
        
        /// <remarks/>
        public string WorkMates {
            get {
                return this.workMatesField;
            }
            set {
                this.workMatesField = value;
            }
        }
        
        /// <remarks/>
        public string WorkDaysAgo {
            get {
                return this.workDaysAgoField;
            }
            set {
                this.workDaysAgoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RunningStyle {
        
        private string runStyle_BRISField;
        
        private int paceRunsField;
        
        private int paceWinsField;
        
        private int offPaceRunsField;
        
        private int offPaceWinsField;
        
        /// <remarks/>
        public string RunStyle_BRIS {
            get {
                return this.runStyle_BRISField;
            }
            set {
                this.runStyle_BRISField = value;
            }
        }
        
        /// <remarks/>
        public int PaceRuns {
            get {
                return this.paceRunsField;
            }
            set {
                this.paceRunsField = value;
            }
        }
        
        /// <remarks/>
        public int PaceWins {
            get {
                return this.paceWinsField;
            }
            set {
                this.paceWinsField = value;
            }
        }
        
        /// <remarks/>
        public int OffPaceRuns {
            get {
                return this.offPaceRunsField;
            }
            set {
                this.offPaceRunsField = value;
            }
        }
        
        /// <remarks/>
        public int OffPaceWins {
            get {
                return this.offPaceWinsField;
            }
            set {
                this.offPaceWinsField = value;
            }
        }
    }
}
